import{performancePractice}from'./performance.js';
import{validateCourse,grade,complete,freshState}from'./core.js';import{Scorm12}from'./scorm.js';import{marked}from'./vendor--marked.esm.js';import DOMPurify from'./vendor--purify.es.mjs';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=decode(text);if(cls)e.className=cls;return e};
function decode(t){const x=document.createElement('textarea');x.innerHTML=String(t??'').replace(/</g,'&lt;');return x.value}
const button=(t,f,cls)=>{const b=el('button',t,cls);b.onclick=f;return b};
function prose(t){const e=el('div',undefined,'prose');e.innerHTML=DOMPurify.sanitize(marked.parse(String(t||'')));for(const a of e.querySelectorAll('a'))a.rel='noopener noreferrer';return e}
function info(t){const p=el('p',t,'feedback');p.setAttribute('role','status');return p}
function rubric(v){if(typeof v==='string')return prose(v);if(Array.isArray(v)){const ul=el('ul');v.forEach(x=>{const li=el('li');li.append(rubric(x));ul.append(li)});return ul}const dl=el('dl',undefined,'rubric');for(const[k,x]of Object.entries(v||{})){dl.append(el('dt',k.replace(/([A-Z])/g,' $1')),el('dd'));dl.lastChild.append(rubric(x))}return dl}
const theme=$('#theme');document.body.dataset.theme=localStorage.getItem('learning-theme')||'blue';theme.value=document.body.dataset.theme;theme.onchange=()=>{document.body.dataset.theme=theme.value;localStorage.setItem('learning-theme',theme.value)};
const params=new URLSearchParams(location.search);let c,state,scorm,key,mode=localStorage.getItem('learning-mode')||'read',events=[],recordState='Progress stays in this browser.',server=false;const preview=params.has('preview');let main;
async function event(verb,details={}){if(preview)return;const e={id:crypto.randomUUID(),verb,courseId:c.id,timestamp:new Date().toISOString(),...details};events.push(e);localStorage.setItem(key+'-pending',JSON.stringify(events));await flush()}
let flushing=false;
async function flush(){if(flushing||!server||!events.length)return;flushing=true;try{while(events.length){const batch=events.slice(0,30);const r=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(batch)});if(!r.ok)throw Error('Learning-record delivery failed');const sent=new Set(batch.map(e=>e.id));events=events.filter(e=>!sent.has(e.id));localStorage.setItem(key+'-pending',JSON.stringify(events));}recordState='Local server received learning events. LRS delivery status is shown in Learning records.'}catch{recordState='Learning events pending. They have not been confirmed in the LRS.'}finally{flushing=false}const p=$('#record-status');if(p)p.textContent=recordState}

function save(){if(preview)return;localStorage.setItem(key,JSON.stringify(state));scorm.save(state,complete(c,state));if(scorm.error)recordState='LMS save error: '+scorm.error}
function go(pos){state.position=pos;save();render();$('#page-title')?.focus();window.scrollTo(0,0)}
function check(q,parent,isActivity=false){
 state.practice??={};const id=q.id||parent.id+'-activity';const prior=state.practice[id]||{};let selected=prior.selected;
 const fs=el('fieldset');fs.append(el('legend',isActivity?'Try a decision':'Check your understanding'),prose(q.prompt));
 const out=el('div');out.setAttribute('aria-live','polite');
 const feedback=()=>{const o=q.options.find(x=>x.id===selected),ok=isActivity?o.isBest:selected===q.correctOptionId;out.replaceChildren(info((ok?'Correct. ':'Review this choice. ')+(isActivity?o.feedback:q.rationale)));return ok};
 for(const o of q.options||[]){const label=el('label',undefined,'choice'),r=el('input');r.type='radio';r.name='q-'+id;r.value=o.id;r.checked=selected===o.id;r.onchange=()=>{selected=o.id;state.practice[id]={selected,submitted:false};save();out.replaceChildren()};label.append(r,el('span',o.text));fs.append(label)}
 fs.append(button('Check response',()=>{if(!selected){out.replaceChildren(info('Choose a response first.'));return}const ok=feedback();state.practice[id]={selected,submitted:true};save();event('answered',{questionId:id,response:selected,success:ok})}),out);
 if(prior.submitted&&selected)feedback();return fs;
}
function navigation(){const aside=el('aside',undefined,'sidebar');aside.setAttribute('aria-label','Course navigation');aside.append(el('p','YOUR LEARNING PATH','eyebrow'),el('h2',c.title));const p=el('progress');p.max=c.lessons.length;p.value=state.visited.length;p.setAttribute('aria-label','Lessons reviewed');aside.append(p,el('p',state.visited.length+' of '+c.lessons.length+' lessons reviewed'));const ol=el('ol');const names=['Overview',...c.lessons.map(l=>l.title),'Assessment','Resources & job aid'];names.forEach((t,i)=>{const li=el('li');const b=button(t,()=>go(i));if(i===state.position)b.setAttribute('aria-current','step');li.append(b);ol.append(li)});aside.append(ol,button('Help',()=>{const d=$('#help');d.open=!d.open;d.scrollIntoView()} ,'secondary'),button('Restart practice',()=>{if(confirm('Start a new practice attempt? This resets course progress in this browser. Previous learning events remain in the record.')){state=freshState();save();event('initialized');render()}},'secondary'));return aside}
function overview(){main.append(el('p','Independent portfolio sample','eyebrow'),heading(c.title),prose(c.summary),el('p',(c.durationNote||'Estimated '+c.durationMinutes+' minutes; learner timing not yet measured.'),'muted'),el('h2','Who this is for'),prose(c.audience),el('h2','What you will practice'));const ul=el('ul');for(const o of c.objectives||[])ul.append(el('li',o.text));main.append(ul,el('h2','Before you begin'));for(const p of c.prerequisites||[])main.append(prose(p));main.append(info(c.disclaimer),button('Begin learning',()=>go(1)))}
function heading(t){const h=el('h1',t);h.id='page-title';h.tabIndex=-1;return h}
function lesson(){
 const l=c.lessons[state.position-1],plan=c.presentation?.lessons?.find(x=>x.lessonId===l.id);
 state.panels??={};let panelIndex=state.panels[l.id]||0;const panels=plan?.panels||[];
 main.append(el('p','Lesson '+state.position+' / '+c.lessons.length,'eyebrow'),heading(l.title));
 const controls=el('div',undefined,'actions');
 const switchMode=m=>{mode=m;localStorage.setItem('learning-mode',m);save();render();document.querySelector('[aria-pressed=true]')?.focus()};
 const rb=button('Read',()=>switchMode('read')),wb=button('Watch',()=>switchMode('watch'));rb.setAttribute('aria-pressed',String(mode==='read'));wb.setAttribute('aria-pressed',String(mode==='watch'));controls.append(rb,wb);main.append(controls);
 let hasVideo=!!(l.media?.videoUrl&&l.media?.captionsUrl);
 if(mode==='watch'){if(hasVideo){const v=el('video');v.controls=true;v.preload='metadata';v.style.width='100%';v.setAttribute('aria-label',l.title+' explainer');v.src=l.media.videoUrl;const tr=el('track');tr.kind='captions';tr.srclang='en';tr.label='English';tr.src=l.media.captionsUrl;tr.default=true;v.append(tr);const err=el('p');err.setAttribute('role','status');v.onerror=()=>err.textContent='Video could not load. Use Read or the full lesson text below.';v.ontimeupdate=()=>{state.videoTimes??={};state.videoTimes[l.id]=v.currentTime};v.onloadedmetadata=()=>v.currentTime=state.videoTimes?.[l.id]||0;main.append(v,err);if(l.media.transcript){const d=el('details');d.append(el('summary','Video transcript'),prose(l.media.transcript));main.append(d)}}else main.append(info('Watch is preparing. A captioned explainer is not available yet. Read remains available below.'))}
 const practice=()=>{if(l.activity){if(l.activity.options?.length)main.append(check(l.activity,l,true));else main.append(el('h2','Practice'),prose(l.activity.prompt))}if(l.knowledgeCheck)main.append(check(l.knowledgeCheck,l));};
 if((mode==='read'||!hasVideo)&&panels.length){panelIndex=Math.min(panelIndex,panels.length-1);const p=panels[panelIndex];const slide=el('section',undefined,'slide '+p.layout);slide.setAttribute('aria-label','Read panel '+(panelIndex+1)+' of '+panels.length);slide.append(el('p','READ '+String(panelIndex+1).padStart(2,'0')+' / '+panels.length,'eyebrow'),el('h2',p.title));const visuals=el(p.layout==='process'?'ol':'div',undefined,'visual-grid');for(const [i,x]of p.copy.entries()){const card=el(p.layout==='process'?'li':'div',undefined,'visual-card');card.append(el('span',String(i+1).padStart(2,'0'),'tag'),el('p',x));visuals.append(card)}slide.append(visuals);
 if(p.diagramData?.kind==='signedBridge'){const d=p.diagramData;const strip=el('ol',undefined,'bridge');for(const x of [{label:'Net income',value:d.start},...d.steps,{label:'EBITDA',value:d.end}]){const li=el('li');li.append(el('strong',x.value),el('span',x.label));strip.append(li)}slide.append(el('p',d.unit),strip)}
 if(p.callout)slide.append(info(p.callout));
 if(p.paragraphs?.length){const reveal=el('details');reveal.append(el('summary','Explore the example'),prose(p.paragraphs.map(n=>l.content.split(/\n\n+/)[n-1]||'').join('\n\n')));slide.append(reveal)}
 main.append(slide);if(p.layout==='practice'||p.activityRef)practice();
 const pc=el('div',undefined,'actions');const back=button('Previous panel',()=>{state.panels[l.id]=panelIndex-1;save();render();$('#page-title').focus()},'secondary');back.disabled=panelIndex===0;const next=button('Next panel',()=>{state.panels[l.id]=panelIndex+1;save();render();$('#page-title').focus()});next.disabled=panelIndex===panels.length-1;pc.append(back,el('span','Panel '+(panelIndex+1)+' of '+panels.length),next);main.append(pc);
 }else if(mode==='read'||!hasVideo)main.append(prose(l.content));
 const full=el('details');full.append(el('summary','Full lesson text'),prose(l.content));main.append(full);
 if(mode==='watch'&&hasVideo||!panels.length)practice();
 const writing=performancePractice({document,course:c,lesson:l,key,storage:localStorage});if(writing)main.append(writing);
 const actions=el('div',undefined,'actions');actions.append(button('Previous lesson',()=>go(state.position-1),'secondary'));
 const advance=button('Mark reviewed and continue',()=>{if(!state.visited.includes(l.id))state.visited.push(l.id);event('experienced',{lessonId:l.id});go(state.position+1)});advance.disabled=!!(panels.length&&(mode==='read'||!hasVideo)&&panelIndex<panels.length-1);actions.append(advance);main.append(actions);
}
function assessment(){main.append(el('p','Apply what you learned','eyebrow'),heading('Knowledge assessment'),prose(c.assessment.instructions||'Answer every question. Pass with '+Math.ceil(c.assessment.questions.length*c.assessment.passPercent/100)+' of '+c.assessment.questions.length+' correct. Untimed; retries permitted.'));if(!c.lessons.every(l=>state.visited.includes(l.id))){main.append(info('Review all lessons before submitting the assessment. You can use the learning path to return to unfinished lessons.'));return}
 const form=el('form');for(const q of c.assessment.questions){const fs=el('fieldset');fs.append(el('legend',q.prompt));for(const o of q.options){const label=el('label',undefined,'choice'),r=el('input');r.type='radio';r.name=q.id;r.value=o.id;r.required=true;r.checked=state.answers[q.id]===o.id;r.onchange=()=>{state.answers[q.id]=o.id;save()};label.append(r,el('span',o.text));fs.append(label)}form.append(fs)}
 const submit=el('button','Submit assessment');submit.type='submit';form.append(submit);form.onsubmit=e=>{e.preventDefault();state.result=grade(c,state.answers);save();for(const q of c.assessment.questions)event('answered',{questionId:q.id,response:state.answers[q.id],success:state.answers[q.id]===q.correctOptionId});event(state.result.passed?'passed':'failed',{score:state.result.percent});if(complete(c,state)&&!state.completionSent){state.completionSent=true;save();event('completed',{score:state.result.percent})}render();$('#assessment-result')?.focus()};main.append(form);
 if(state.result){const result=el('section',undefined,'result');result.id='assessment-result';result.tabIndex=-1;result.setAttribute('aria-live','polite');result.append(el('h2',state.result.passed?'Practice assessment passed':'Keep practicing'),el('p',state.result.correct+' / '+state.result.total+' correct ('+state.result.percent.toFixed(1)+'%). '+(complete(c,state)?'Course practice completed.':'Course practice incomplete.')),el('p','This result is not professional certification or proof of workplace competence.'));for(const q of c.assessment.questions)result.append(el('h3',q.prompt),prose(q.rationale));result.append(button('Retry assessment',()=>{state.answers={};state.result=null;save();render();$('#page-title').focus()}));main.append(result)}}
function resources(){main.append(heading('Resources & job aid'));const ul=el('ul');for(const x of c.jobAid||[])ul.append(el('li',x));main.append(ul,el('h2','Sources'));for(const r of c.resources||[]){const p=el('p'),a=el('a',r.title);a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';p.append(a,el('br'),document.createTextNode(r.note||''));main.append(p)}main.append(prose(c.disclaimer),button('Print job aid',()=>window.print()))}
function render(){const layout=el('div',undefined,'layout');main=el('main',undefined,'course-main');main.id='main';layout.append(navigation(),main);$('#app').replaceChildren(layout);if(!state.position)overview();else if(state.position<=c.lessons.length)lesson();else if(state.position===c.lessons.length+1)assessment();else resources();const help=el('details');help.id='help';help.append(el('summary','Learning help'),prose('Use Read or Watch to choose a presentation mode without resetting progress. Mark each lesson reviewed, then submit the assessment. Use the learning path to revisit material. Read mode contains the full instructional text. Writing notes remain on this browser and are not assessed automatically.'));main.append(help);const status=el('p',preview?'Draft preview — no learning records are sent.':recordState,'status');status.id='record-status';status.setAttribute('role','status');main.append(status)}
async function start(){if(params.get('course')||preview){c=preview?JSON.parse(localStorage.getItem('author-preview')):await(await fetch('courses--'+encodeURIComponent(params.get('course'))+'.json')).json();const errors=validateCourse(c);if(errors.length)throw Error(errors.join('; '));try{const r=await fetch('storyboards--'+c.id+'.json');if(r.ok){const raw=await r.json();c.presentation=raw.courses?.find(x=>x.courseId===c.id)||raw;for(const l of c.presentation.lessons||[])for(const p of l.panels||[])p.paragraphs??=p.sourceContentMapping?.paragraphNumbersOneBased||[]}}catch{}try{const r=await fetch('media--'+c.id+'--manifest.json');if(r.ok){const m=await r.json();for(const l of c.lessons)l.media=m.lessons?.find(x=>x.lessonId===l.id)||l.media}}catch{}if(c.brand?.theme&&!localStorage.getItem('learning-theme')){document.body.dataset.theme=c.brand.theme;theme.value=c.brand.theme}document.title=c.title+' | Learning studio';key='course-'+c.id+'-'+(c.version||'1');scorm=new Scorm12();state=scorm.init();if(!state){try{state=JSON.parse(localStorage.getItem(key))}catch{}}state={...freshState(),...state};state.position=Math.min(Math.max(Number(state.position)||0,0),c.lessons.length+2);state.visited=state.visited.filter(id=>c.lessons.some(l=>l.id===id));events=JSON.parse(localStorage.getItem(key+'-pending')||'[]');try{server=(await fetch('/api/health')).ok}catch{}render();event('initialized');window.addEventListener('online',flush);window.addEventListener('pagehide',()=>{save();scorm.finish()});}
 else{const cs=await(await fetch('courses--index.json')).json();main=el('main');main.id='main';const intro=el('section',undefined,'intro');intro.append(el('p','Lorne · Learning portfolio','eyebrow'),heading('Practice the decisions that matter.'),el('p','Explore original workplace scenarios, worked examples and useful feedback. Seven subjects. One consistent learning experience.'));main.append(intro);const grid=el('div',undefined,'grid');for(const x of cs){const card=el('article',undefined,'card');card.append(el('span',x.durationMinutes+' min · estimated','tag'),el('h2',x.title),el('p',x.summary));const a=el('a','Open course','button');a.href='?course='+x.id;card.append(a);grid.append(card)}main.append(grid,info('Independent portfolio samples. Public playback stores progress in your browser. An operational deployed LMS/LRS is not yet available.'));$('#app').replaceChildren(main)}}
start().catch(e=>{$('#app').replaceChildren(el('main','Unable to load course: '+e.message,'error'))});
